version: '3'
services:
  manga-services:
    build: './services'
    depends_on:
      - manga-svc-db
    environment:
      - DB_URL=mysql://root:VQTmFnwGbO@listings-svc-db/db?charset=UTF8
    ports:
      - 3001:3001
    volumes:
      - ./services:/opt/app
  manga-svc-db:
    environment:
      - MYSQL_ROOT_PASSWORD=VQTmFnwGbO
      - MYSQL_DATABASE=db
      - MONGODB_URL=mongodb://localhost:37017/manga-reader-react-svc
    image: mongo:4.2.7
    ports:
      - 0.0.0.0:37017:27017
